// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sutxjoojzhwrtomojgob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dHhqb29qemh3cnRvbW9qZ29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3OTc3NDAsImV4cCI6MjA1ODM3Mzc0MH0.DrPkD6DaZDOEl5xY45DEkh7HAqhBVIws4WaewEyPxYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);